### ISSUE TITLE
midihub shutsdown 5 seconds if you power it up by external battery pack

### ISSUE THREAD

**Issue by cereyanli** [hotchk155/MIDI-Hub#5]
I am using a usb batery pack to power the device up but device is shutting off after couple of seconds and I assume this is battery i is shutting itself off due to midihub power consumption so low and it thinks there is nothing connected to it.

Is there anything do about it?

**Comment by hotchk155** [comment]
Hi

I’ve not heard of this issue before, but did some Googling and yeah I think you are right, the power consumption will be pretty low on the Midi Hub.

This is an interesting article about the issue
https://www.dorkbotpdx.org/blog/paul/battery_pack_load

and I found a commercial product that does the same
http://www.sotabeams.co.uk/usb-battery-pack-keep-alive-load-kit/

I was wondering if attaching a filament torch/flashlight bulb or several LEDs (with resistors) between the MIDI hub GND/5V pads might also do the trick. Could be worth a try

Another option is to use standard alkaline batteries – you can probably run it reliably on 4.5V (three cells) for a decent amount of time

Cheers
Jason

**Comment by hotchk155** [comment]
Not a bug - would recommend running from normal alkaline batteries at 4.5V instead
